language: php

php:
  - 7.0
  - 7.1
  - 7.2

env:
  global:
    - REPO_NAME=cakephp-vat-number-check-webservice
    - PLUGIN_NAME=VatNumberCheck
    - REQUIRE=""
    - DB=mysql CAKE_VERSION=2

  matrix:
    - DB=mysql CAKE_VERSION=2.6
    - DB=mysql CAKE_VERSION=2.7
    - DB=mysql CAKE_VERSION=2.8
    - DB=mysql CAKE_VERSION=2.9
    - DB=mysql CAKE_VERSION=2.10

matrix:
  include:
    - php: 7.1
      env:
        - CODECOVERAGE=1
    - php: 7.1
      env:
        - PHPCS=1
    - php: 7.1
      env:
        - FOC_VALIDATE=1
  exclude:
    - php: 7.0
      env: DB=mysql CAKE_VERSION=2.6
    - php: 7.0
      env: DB=mysql CAKE_VERSION=2.7
    - php: 7.0
      env: DB=mysql CAKE_VERSION=2.8
    - php: 7.1
      env: DB=mysql CAKE_VERSION=2.6
    - php: 7.1
      env: DB=mysql CAKE_VERSION=2.7
    - php: 7.1
      env: DB=mysql CAKE_VERSION=2.8
    - php: 7.2
      env: DB=mysql CAKE_VERSION=2.6
    - php: 7.2
      env: DB=mysql CAKE_VERSION=2.7
    - php: 7.2
      env: DB=mysql CAKE_VERSION=2.8
    - php: 7.2
      env: DB=mysql CAKE_VERSION=2.9

branches:
  only:
    - master

before_script:
  - git clone -b master https://github.com/Oefenweb/travis --depth 1 ../travis
  - travis_wait ../travis/before_script.sh
  - |
    cat <<'  EOF' > ../cakephp/app/Config/database.php
    <?php
    class DATABASE_CONFIG {
      protected $_identities = [
        'mysql' => [
          'datasource' => 'Database/Mysql',
          'host' => '0.0.0.0',
          'login' => 'travis'
        ],
        'pgsql' => [
          'datasource' => 'Database/Postgres',
          'host' => '127.0.0.1',
          'login' => 'postgres',
          'database' => 'cakephp_test',
          'schema' => [
            'default' => 'public',
            'test' => 'public',
          ]
        ],
        'sqlite' => [
          'datasource' => 'Database/Sqlite',
          'database' => [
            'default' => ':memory:',
            'test' => ':memory:',
          ]
        ]
      ];

      public $default = [
        'persistent' => false,
        'host' => '',
        'login' => '',
        'password' => '',
        'database' => 'cakephp_test',
        'prefix' => ''
      ];

      public $test = [
        'persistent' => false,
        'host' => '',
        'login' => '',
        'password' => '',
        'database' => 'cakephp_test',
        'prefix' => ''
      ];

      public $vatNumberCheckWebservice = [
        'datasource' => 'VatNumberCheck.SoapSource',
        'wsdl' => 'http://ec.europa.eu/taxation_customs/vies/checkVatService.wsdl',
      ];

      public function __construct() {
        $db = 'mysql';
        if (!empty($_SERVER['DB'])) {
          $db = $_SERVER['DB'];
        }

        foreach (['default', 'test'] as $source) {
          $config = array_merge($this->{$source}, $this->_identities[$db]);
          if (is_array($config['database'])) {
            $config['database'] = $config['database'][$source];
          }
          if (!empty($config['schema']) && is_array($config['schema'])) {
            $config['schema'] = $config['schema'][$source];
          }
          $this->{$source} = $config;
        }
      }
    }
    EOF
  - cat ../cakephp/app/Config/database.php

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: false
  hipchat:
    rooms:
      secure: tfUbHwPzFhLKQ3wcrX/P5nAUC6gNRq34Zu4ha81+HnF7lOH5FWkMTPKQIblatlekShGg3tviXHLws0Kw8YIQISRvECY+leqXA8/uxlwlJqqt5+Ve8JWbtc93vw0x0PEH88w5JUSAD8uMQNTQze6opXExnRSFNxw0P7W8r2IWs8zLkcfmkMkbGy01HJw/zd+cVaRP2r5pn03xb/bToYtKDv9yHPV5tBmMirkC8YFkL1gtaXZzW6yyNwnCGKYKG3bxbhxYlGMxEQ3lM/j8BYZ5Q7jvr91Eb2Xj7Q31CKFQusyGvoEEbEQQqY9xPpxotuX28zwjmrj3jCGKhcr3WjiL2SVlpWFutebc+qYhsCN7GO0exnmcKAKMxUb/mEWXGog1gkWwBZsxqqh9rHgJzaQwhFSB2q+khEP7oi6sO9kmrBb3IOZ0Dv3T9JEi6iVnYaA/Xmm4S14gL06fL+Xcz91GvBOmC8c1ufhI3+f1zJykSUo91qgLYVHzQqwVH6VH3xxk3cqH0WC7GE7r5V6X9QIxgFvgyMXNbSTSbDidpaHVb565CqK4yDAAL5KOdRZFUSwxlTx3Q9YnL8HOa+57O2+8kdzImiI83495g8fSMk9DQit2heIzQbKJjj6nOXCtxuMWw/bo6K1+UsA9WCovBcjtXeGANeMXsfXl43W/jF5QYsA=
