language: php

services:
  - mysql

php:
  - 7.0
  - 7.1
  - 7.2

env:
  global:
    - REPO_NAME=cakephp-vat-number-check-webservice
    - PLUGIN_NAME=VatNumberCheck
    - REQUIRE=""
    - DB=mysql CAKE_VERSION=2

    - secure: "keMhRIfM1NuAhWMD70dwCk1juxZF7W8TwQUSMwjTD1aaOK4XRqhd/F5Ix6TGY1n8FRyLkQa0J906ACHm4UoZqkuoreM+CTx1TD7GVL+BkWFi4rwWW8fDC9MtNx4/2kYEtVAGqu5bbxT4rQ7Iq3o4qwLfKRGI8VJNBa7/BnPHZ9QzQ8wibJf3zb6qsDIL6fKfFtK2qxLzb3fqahs5KXOp76+1Nr91eqr0UznjWNFt8pGLL0+HLiaWUCmvurSigRQUsinM7m6K+1xQJpdsSL4HTHt9luWJYVZsgkqeZFueHMMXHt9AOBGzTsCWJJgZMOu/5w4IRx28Q6CSs+cwR2F3xC7pXAyeMkZcqgEICnm6tF5xu7hcyEtGcFbqhEojDroSrJYtCmYzutF5rXCqZ+niS0iNL9DB044+rrG5/unddxdvXgCVv4zkKfEIavtkBuT1jfSx3ITEPhmsoNpr7zk013LBanAUhdg9hCcxGARjWDKFQsM83d5rzFo/vxPAlZXRu21NNX0XMeQ8dgX0VE/kRPUNEMDMUhvpcKMbKcrnbV9VtCKktZLwa7bEtMpCW1Cdo7ZKyaFSjpTdQcLU4M1sMGthURB7gf3bs1o+EU3qYaZGdOIcMNxNTUlt7HODMVXXhzjCm3HSPffs7nhoM5NAfP7GojkYN8n7V92EcEpR1hU="

  matrix:
    - CAKE_VERSION=2.9
    - CAKE_VERSION=2.10 PHPUNIT_VERSION=^5.7

matrix:
  include:
    - php: 7.1
      env:
        - CODECOVERAGE=1 PHPUNIT_VERSION=^5.7
    - php: 7.1
      env:
        - PHPCS=1
    - php: 7.1
      env:
        - FOC_VALIDATE=1
  exclude:
    - php: 7.2
      env: CAKE_VERSION=2.9

branches:
  only:
    - master
    - 2.x
    - 3.x

before_script:
  - git clone -b master https://github.com/Oefenweb/travis --depth 1 ../travis
  - travis_wait ../travis/before_script.sh

  - mkdir -p ../cakephp/app/Config
  - |
    cat <<'  EOF' > ../cakephp/app/Config/database.php
    <?php
    class DATABASE_CONFIG {
      protected $_identities = [
        'mysql' => [
          'datasource' => 'Database/Mysql',
          'host' => '127.0.0.1',
          'login' => 'travis'
        ],
        'pgsql' => [
          'datasource' => 'Database/Postgres',
          'host' => '127.0.0.1',
          'login' => 'postgres',
          'database' => 'cakephp_test',
          'schema' => [
            'default' => 'public',
            'test' => 'public',
          ]
        ],
        'sqlite' => [
          'datasource' => 'Database/Sqlite',
          'database' => [
            'default' => ':memory:',
            'test' => ':memory:',
          ]
        ]
      ];

      public $default = [
        'persistent' => false,
        'host' => '',
        'login' => '',
        'password' => '',
        'database' => 'cakephp_test',
        'prefix' => ''
      ];

      public $test = [
        'persistent' => false,
        'host' => '',
        'login' => '',
        'password' => '',
        'database' => 'cakephp_test',
        'prefix' => ''
      ];

      public $vatNumberCheckWebservice = [
        'datasource' => 'VatNumberCheck.SoapSource',
        'wsdl' => 'http://ec.europa.eu/taxation_customs/vies/checkVatService.wsdl',
      ];

      public function __construct() {
        $db = 'mysql';
        if (!empty($_SERVER['DB'])) {
          $db = $_SERVER['DB'];
        }

        foreach (['default', 'test'] as $source) {
          $config = array_merge($this->{$source}, $this->_identities[$db]);
          if (is_array($config['database'])) {
            $config['database'] = $config['database'][$source];
          }
          if (!empty($config['schema']) && is_array($config['schema'])) {
            $config['schema'] = $config['schema'][$source];
          }
          $this->{$source} = $config;
        }
      }
    }
    EOF
  - |
    echo 'default_socket_timeout = 60' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: false
