language: php

sudo: false

php:
  - 7.1

env:
  global:
    - CAKE_VERSION=^3.8.0

services:
  - mysql

matrix:
  include:
    - php: 7.1
      env:
        - PHP_SYNTAX=1
    - php: 7.1
      env:
        - PHP_CS=1
    - php: 7.1
      env:
        - PHP_CPD=1
    - php: 7.1
      env:
        - PHP_MD=1
    - php: 7.1
      env:
        - PHP_STAN=1
    - php: 7.1
      env:
        - PHP_PHAN=1
    - php: 7.1
      env:
        - PHP_COVERAGE=1

branches:
  only:
    - master
    - 2.x
    - 3.x

before_script:
  - travis_wait ./.travis/before-script.sh

script:
  - ./.travis/script.sh

after_success:
  - ./.travis/after-success.sh
